package com.macro.mall.portal.aftersale.core;

public enum AfterSaleStatus {
    DRAFT, WAITING_USER_CONFIRMATION, SUBMITTED, WAITING_STAFF_APPROVAL,
    WAITING_SUPERVISOR_APPROVAL, APPROVED, REJECTED, EXECUTING, RETRY_PENDING,
    COMPLETED, FAILED, MANUAL_RECONCILIATION, CANCELLED
}
