<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { AgentClient, type AssignmentOffer, type QueueItem, type ConversationSummary, type CopilotSuggestion } from '@aliagent/api-client'
const client = new AgentClient(); const state = reactive({ presence: 'OFFLINE', offers: [] as AssignmentOffer[], queue: [] as QueueItem[], conversations: [] as ConversationSummary[], suggestion: null as CopilotSuggestion | null, pendingAction: '' }); const selected = ref<ConversationSummary | null>(null); const draft = ref('')
const capacity = computed(() => `${state.conversations.length} 个进行中会话`)
async function load() { [state.offers, state.queue, state.conversations] = await Promise.all([client.offers(), client.queue(), client.conversations()]) }
async function run(key: string, action: () => Promise<unknown>) { if (state.pendingAction) return; state.pendingAction = key; try { await action(); await load() } catch (error) { alert(error instanceof Error ? error.message : '请求失败，请重试') } finally { state.pendingAction = '' } }
async function select(c: ConversationSummary) { selected.value = c; state.suggestion = await client.suggestion(c.conversationId).catch(() => null); draft.value = state.suggestion?.content ?? '' }
load().catch(() => undefined)
</script>
<template><main><header><h1>客服工作台</h1><select v-model="state.presence"><option>OFFLINE</option><option>ONLINE</option><option>BUSY</option></select><span>{{ capacity }}</span></header><section class="grid"><aside><h2>我的邀请</h2><p v-for="offer in state.offers" :key="offer.offerId">{{ offer.skillGroupName }} · {{ new Date(offer.expiresAt).toLocaleTimeString() }} <button :disabled="!!state.pendingAction" @click="run(offer.offerId,()=>client.acceptOffer(offer.offerId))">接受</button></p><h2>队列</h2><p v-for="item in state.queue" :key="item.queueItemId">{{ item.title }} <button :disabled="!!state.pendingAction" @click="run(item.queueItemId,()=>client.claim(item.queueItemId))">领取</button></p></aside><article><h2>已接管会话</h2><button v-for="c in state.conversations" :key="c.conversationId" @click="select(c)">{{ c.title }} / {{ c.customerName }}</button><template v-if="selected"><h2>{{ selected.title }}</h2><p>订单：{{ selected.orderSummary }}</p><p>物流：{{ selected.logisticsSummary }}</p><p>售后：{{ selected.afterSaleSummary }}</p><textarea v-model="draft" placeholder="输入人工回复"></textarea><button>发送</button><button>转派</button><button>结束</button><button>关闭</button></template></article><aside><h2>AI 副驾</h2><template v-if="selected"><p v-if="state.suggestion?.status==='FAILED_RETRYABLE'">依赖暂不可用，可重试。</p><textarea v-model="draft"></textarea><p v-for="citation in state.suggestion?.citations" :key="citation.source">{{ citation.title }}</p><button :disabled="!!state.pendingAction" @click="run('refresh',()=>client.refresh(selected!.conversationId))">刷新</button><button v-if="state.suggestion" :disabled="!!state.pendingAction" @click="run('accept',()=>client.action(state.suggestion!.suggestionId,'accept'))">采纳</button><button v-if="state.suggestion" :disabled="!!state.pendingAction" @click="run('modify',()=>client.action(state.suggestion!.suggestionId,'modify-and-send',draft))">编辑发送</button><button v-if="state.suggestion" :disabled="!!state.pendingAction" @click="run('ignore',()=>client.action(state.suggestion!.suggestionId,'ignore'))">忽略</button></template></aside></section></main></template>
