package com.bn.aliagent.orchestration.aftersale;

public enum AfterSaleStatus {
    WAITING_USER_CONFIRMATION, WAITING_STAFF_APPROVAL, WAITING_SUPERVISOR_APPROVAL,
    EXECUTING, RETRY_PENDING, PROCESSING, COMPLETED, FAILED, MANUAL_RECONCILIATION,
    UNKNOWN, HUMAN_HANDOFF
}
